# Commandline calling for testing:
# ansible-playbook  --inventory  x_scr_testing_inventory_X90.yaml     \
#                   --inventory  x_scr_testing_inventory_X91.yaml     \
#                   --extra-vars @x_scr_parameters.yaml               \
#                   playbook_scr_mkd_testing.yaml                     \
#                   -vvv

---
# /*----------------------------------------------------------------------------8
# |                                                                            |
# |           Play for performing SAP System Copy tasks on Source              |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
- hosts:                                "{{ scr_source_sid | upper }}_PAS :
                                         {{ scr_source_sid | upper }}_DB  :
                                         {{ scr_dest_sid   | upper }}_PAS :
                                         {{ scr_dest_sid   | upper }}_DB"

  name:                                 "SCR Source"
  gather_facts:                         false                                    # Important to collect hostvars information
  any_errors_fatal:                     true

  vars:
    # If you're using a user-assigned managed identity, set this:
    # msi_client_id:                      "<user-assigned-mi-client-id>"   # optional



# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                        Retrieve KeyVault Secrets                           |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
# Added ansible-galaxy collection install of azure.azcollection to configure_deployer.sh
# Added ansible-galaxy collection install of azure.azcollection to configure_deployer.sh.tmpl

  pre_tasks:
    - name:                             "Source - Get the SSH credentials for the SAP system from Key Vault"
      ansible.builtin.include_role:
        name:                           roles-scr/scr_keys
      vars:
        function:                       "source"                                                    # source or dest
        granularity:                    "workload"                                                  # workload | sid | host
        kv_name:                        "{{ lookup('vars', 'scr_' + function + '_kv_name') }}"      # scr_source_kv_name
        prefix:                         "{{ lookup('vars', 'scr_' + function + '_prefix' ) }}"      # scr_source_prefix
      when:                             
        - (vars['scr_' + function + '_sid'] | upper) + '_PAS' in vars['group_names'] or
          (vars['scr_' + function + '_sid'] | upper) + '_DB'  in vars['group_names']                # source or destination groups


    - name:                             "Destination - Get the SSH credentials for the SAP system from Key Vault"
      ansible.builtin.include_role:
        name:                           roles-scr/scr_keys
      vars:
        function:                       "dest"                                                      # source or dest
        granularity:                    "workload"                                                  # workload | sid | host
        kv_name:                        "{{ lookup('vars', 'scr_' + function + '_kv_name') }}"      # scr_source_kv_name
        prefix:                         "{{ lookup('vars', 'scr_' + function + '_prefix' ) }}"      # scr_source_prefix
      when:                             
        - (vars['scr_' + function + '_sid'] | upper) + '_PAS' in vars['group_names'] or
          (vars['scr_' + function + '_sid'] | upper) + '_DB'  in vars['group_names']                # source or destination groups



# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here.
#
# -------------------------------------+---------------------------------------8
  tasks:
    - name:                             Ping using the fetched key
      ansible.builtin.ping:

    - name:                             "Source - Inventory SAP Kernel Files for SID"
      include_role:
        name:                           roles-scr/scr_kernel
      vars:
        function:                       "inventory"                                                 #
        kernel:                         "sap"                                                       # sap or db (hana, oracle, etc.)
        sapsid:                         "{{ scr_source_sid }}"                                      # SID
      when:                             
        - (sapsid | upper + '_PAS') in vars['group_names'] or
          (sapsid | upper + '_DB')  in vars['group_names']                  # source or destination groups


    - name:                             "Destination - Inventory SAP Kernel Files for SID"
      include_role:
        name:                           roles-scr/scr_kernel
      vars:
        function:                       "inventory"                                                 #
        kernel:                         "sap"                                                       # sap or db (hana, oracle, etc.)
        sapsid:                         "{{ scr_dest_sid }}"                                        # SID
      when:                             
        - (sapsid | upper + '_PAS') in vars['group_names'] or
          (sapsid | upper + '_DB')  in vars['group_names']                  # source or destination groups


    - name:                             "Destination - Compare SAP Kernel Files for SID"
      include_role:
        name:                           roles-scr/scr_kernel
      vars:
        function:                       "compare"                                                   #
        kernel:                         "sap"                                                       # sap or db (hana, oracle, etc.)
        # sapsid:                         "{{ scr_dest_sid }}"                                        # SID
      run_once:                         true
      # when:                             
      #   - (sapsid | upper + '_PAS') in vars['group_names'] or
      #     (sapsid | upper + '_DB')  in vars['group_names']                  # source or destination groups



# Database in progress, but commenting out for now to focus on SAP inventory first. Will add back in once we have the DB inventory tasks fleshed out and tested.
    # - name:                             "Source - Inventory Database Kernel Files for SID"
    #   include_role:
    #     name:                           roles-scr/scr_kernel
    #   vars:
    #     function:                       "inventory"                                                 #
    #     kernel:                         "db"                                                        # sap or db (hana, oracle, etc.)
    #     sapsid:                         "{{ scr_source_sid }}"                                      # SID
    #   when:                             
    #     - (sapsid | upper + '_PAS') in vars['group_names'] or
    #       (sapsid | upper + '_DB')  in vars['group_names']                  # source or destination groups


    # - name:                                 "Test"
    #   ansible.builtin.debug:
    #     msg: |-
    #                                     sapservices_path:           {{ sapservices_path     | default('-')  }}
    #                                     sapservices_lines:          {{ sapservices_lines    | default('-') }}
    #                                     sap_start_facility:         {{ sap_start_facility   | default('-') }}
    #                                     sap_systemd_units:          {{ sap_systemd_units    | default('-') }}
    #                                     sap_unit:                   {{ sap_unit             | default('-') }}
    #                                     sap_pf:                     {{ sap_pf               | default('-') }}
    #                                     sap_system_name:            {{ sap_system_name      | default('-') }}
    #                                     sap_system:                 {{ sap_system           | default('-') }}
    #                                     sap_instance_name:          {{ sap_instance_name    | default('-') }}
    #     verbosity:                      0




# # /*---------------------------------------------------------------------------8
# # |                                                                            |
# # |                         Clean Up Temp Key File                             |
# # |                                                                            |
# # +------------------------------------4--------------------------------------*/
  post_tasks:
    - name:                               "Source - Cleanup the SSH credential files from the OS"
      ansible.builtin.include_role:
        name:                             roles-scr/scr_keys
      vars:
        cleanup:                          true
        function:                         "source"
      when:                             
        - (vars['scr_' + function + '_sid'] | upper) + '_PAS' in vars['group_names'] or
          (vars['scr_' + function + '_sid'] | upper) + '_DB'  in vars['group_names']                # source or destination groups

    - name:                               "Destination - Cleanup the SSH credential files from the OS"
      ansible.builtin.include_role:
        name:                             roles-scr/scr_keys
      vars:
        cleanup:                          true
        function:                         "dest"
      when:                             
        - (vars['scr_' + function + '_sid'] | upper) + '_PAS' in vars['group_names'] or
          (vars['scr_' + function + '_sid'] | upper) + '_DB'  in vars['group_names']                # source or destination groups



































# # /*----------------------------------------------------------------------------8
# # |                                                                            |
# # |           Play for performing SAP System Copy tasks on Target              |
# # |                                                                            |
# # +------------------------------------4--------------------------------------*/
# - name:                                 SCR Destination
#   hosts:                                "{{ scr_dest_sid | upper }}_PAS :
#                                          {{ scr_dest_sid | upper }}_DB"

#   remote_user:                          "{{ scr_dest_ssh_username | default('azureadm') }}"
#   gather_facts:                         false                                    # Important to collect hostvars information
#   any_errors_fatal:                     true

#   vars:
#     function:                           "dest"                                # source or dest
#     # keyvault_uri:                       "https://<your-vault-name>.vault.azure.net/"
#     # private_key_secret_name:            "<secret-name-for-private-key>"
#     # If you're using a user-assigned managed identity, set this:
#     # msi_client_id:                      "<user-assigned-mi-client-id>"   # optional

# # /*---------------------------------------------------------------------------8
# # |                                                                            |
# # |                        Retrieve KeyVault Secrets                           |
# # |                                                                            |
# # +------------------------------------4--------------------------------------*/
# # sudo -H "$${ansible_venv_bin}/ansible-galaxy" collection install azure.azcollection --force --collections-path "$${ansible_collections}"
# # /opt/ansible/venv/2.16/bin/ansible-galaxy collection install azure.azcollection --force --collections-path /opt/ansible/collections
# # /opt/ansible/venv/2.16/bin/pip3 install -r /opt/ansible/collections/ansible_collections/azure/azcollection/requirements.txt
#   pre_tasks:
#     - name:                             "Destination - Get the SSH credentials for the SAP system from Key Vault"
#       ansible.builtin.include_role:
#         name:                           roles-scr/scr_keys
#       vars:
#         function:                       "dest"                                  # source or dest
#         prefix:                         "{{ scr_dest_prefix }}"
#         kv_name:                        "{{ scr_dest_kv_name }}"


# # -------------------------------------+---------------------------------------8
# #
# # Build the list of tasks to be executed in order here.
# #
# # -------------------------------------+---------------------------------------8
#   tasks:
#     - name:                             Ping using the fetched key
#       ansible.builtin.ping:

#     # - name:                             "Source - Inventory SAP Kernel Files for SID"
#     #   include_role:
#     #     name: roles-scr/scr_kernel
#     #   vars:
#     #     scr_function:                   "source"                                # source or dest
#     #     scr_sid:                        "{{ scr_sap_sid_source | upper }}"      # SID
#     #   # when: actual_discovery_mode in ['source', 'both']
#     #   # tags: scr_source_discovery


# # /*---------------------------------------------------------------------------8
# # |                                                                            |
# # |                         Clean Up Temp Key File                             |
# # |                                                                            |
# # +------------------------------------4--------------------------------------*/
#   post_tasks:
#     - name:                             "Source - Get the SSH credentials for the SAP system from Key Vault"
#       ansible.builtin.include_role:
#         name:                           roles-scr/scr_keys
#       vars:
#         function:                       "source"
#         kv_name:                        "{{ scr_kv_name_source }}"
#         prefix:                         "{{ scr_prefix_source }}"
...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
