---
# -------------------------------------+---------------------------------------8
# scr_sap_sid_source:                     "X90"
# scr_sap_sid_dest:                       "X91"
# scr_kv_name_source:                     "MKDS1EUS2SAP00user54B"
# scr_kv_name_dest:                       "MKDS1EUS2SAP00user54B"
# scr_prefix_source:                      "MKDS1-EUS2-SAP00"
# scr_prefix_dest:                        "MKDS1-EUS2-SAP00"
# orchestration_ansible_user:             "azureadm"

# Testing
# keyvault_uri:                           "https://mkds1eus2sap00user54b.vault.azure.net/"
# private_key_secret_name:                "MKDS1-EUS2-SAP00-sid-sshkey"


scr_source_sid:                         "X90"
scr_source_prefix:                      "MKDSE-SECE-SAP00"
scr_source_kv_name:                     "mkdsesecesap00user2f8"
# scr_source_ssh_username:                "azureadm"
# scr_source_ssh_private_key_file:        "/tmp/ansible_kv_key_{{ inventory_hostname }}"
  
scr_dest_sid:                           "X91"
scr_dest_prefix:                        "MKDSE-SECE-SAP00"
scr_dest_kv_name:                       "MKDSESECESAP00user2f8"
# scr_dest_ssh_username:                  "azureadm"
# scr_dest_ssh_private_key_file:          "/tmp/ansible_kv_key_{{ inventory_hostname }}"
