X91_DB:
  hosts:
    x91dhdb00l037:
      ansible_host        : 10.111.96.8
      ansible_user        : azureadm
      ansible_connection  : ssh
      connection_type     : key
      virtual_host        : x91dhdb00l037
      become_user         : root
      os_type             : linux
      vm_name             : MKDS1-EUS2-SAP00-X91_x91dhdb_z3_00l0379
      resource_group_name : MKDS1-EUS2-SAP00-X91
      subscription_id     : 02993e58-2910-4b39-910c-aeccd207abf7
      use_nvme_disks      : false

  vars:
    node_tier             : hana
    supported_tiers       : [hana]

X91_SCS:
  hosts:
    x91scs00l379:
      ansible_host        : 10.111.32.14
      ansible_user        : azureadm
      ansible_connection  : ssh
      connection_type     : key
      virtual_host        : x91scs00l379
      become_user         : root
      os_type             : linux
      vm_name             : MKDS1-EUS2-SAP00-X91_x91scs_z3_00l379
      resource_group_name : MKDS1-EUS2-SAP00-X91
      subscription_id     : 02993e58-2910-4b39-910c-aeccd207abf7
      use_nvme_disks      : false

  vars:
    node_tier             : scs
    supported_tiers       : [scs]

X91_ERS:
  hosts:
  vars:
    node_tier             : ers
    supported_tiers       : [ers]

X91_PAS:
  hosts:
    x91app00l379:
      ansible_host        : 10.111.32.17
      ansible_user        : azureadm
      ansible_connection  : ssh
      connection_type     : key
      virtual_host        : x91app00l379
      become_user         : root
      os_type             : linux
      vm_name             : MKDS1-EUS2-SAP00-X91_x91app_z3_00l379
      resource_group_name : MKDS1-EUS2-SAP00-X91
      subscription_id     : 02993e58-2910-4b39-910c-aeccd207abf7
      use_nvme_disks      : false

  vars:
    node_tier             : pas
    supported_tiers       : [pas]

X91_APP:
  hosts:
  vars:
    node_tier             : app
    supported_tiers       : [app]

X91_WEB:
  hosts:
  vars:
    node_tier             : web
    supported_tiers       : [web]

X91_OBSERVER_DB:
  hosts:
  vars:
    node_tier             : observer
    supported_tiers       : [observer]

X91_ISCSI:
  hosts:
  vars:
    node_tier             : iscsi
    supported_tiers       : [iscsi]
